version: "3.7"

services:
  notifications:
    image: notifications
    restart: always
    ports:
      - 3032:3000
    environment:
      QSHN_ENV: development
      QSHN_PORT: 3000
      QSHN_DBHOST: localhost
      QSHN_DBPORT: 27017
      QSHN_DBNAME: qliknotifications
      QSHN_DBUSER: root
      QSHN_DBPASS: example

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
